server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5400/fsj
    username: postgres
  main:
    lazy-initialization: true
  jpa:
    hibernate:
      #ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
